sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-lang-czechslovak
  lmodern
script: make
deploy:
  provider: releases
  api_key:
    secure: KhnCqoXkqUabkkIRteICDZJbOo5z44eagzKNwiyt3VBdGZSOmsoFCnr3Er2awPQFqZxpOlHDBdmbzQdEaWRr0FNLuB1b/8k/25nA0RPu85UQG8VDWvkQzqitYGvLDVnvDYpmb0QxcL8iN5U/RaX1j7n6p3wpc5sI1UAq7e4tSPWgTkBlVT5GdTeaZvC80Q3mHZssOqAZmRqAzbDvToVuXv2+6Vy9OBMpoRf3XC/MNsRgADMSQhNxSEoaEBerZcC0VwuLGNKcNbew/aFI2c+QCqUEBbVGpyoiZeqVjt+WSmH1uvmON2X6ZjsD8FOncbSAw/5B8UlwcTuh9IjjiDzPp0dkyTGpC37WGrIGSd8CLOMUCB8tN1WlMKcAYZongkSiNL/g+DqylMSpRdDR5un0W6D+vV6B5tWphMktxC5nYaDRTRPL6plS7/ccwbV8+036+rFcdtHWj6vHmaG2uQFuZ7+Im0psS8S2PDs3johDcpZ1BcIOYMdp9vYR+IQRJhcFyw0mSnBIvDD56itW2dQf8fzmqgXbwRkDH0zk1S0n/AX3Zm87zY8+Iq2m9utHzMMBAzG75TYbiW18e2anl5lRt9KiAIrg7snS+fHwfozJZoMOF4x1fP463+CsEgXKh5eDgeic2k7lhyjF2mJ4KRbGxc6xIt6DfD/vbBcjU1U1s2A=
  file: hJOPquiz.pdf
  skip_cleanup: true
  on:
    tags: true
