sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-lang-czechslovak
  lmodern
script: make
deploy:
  provider: releases
  api_key:
    secure: NTGUfP7/F4m9JOmj/NM7OjSItR9gR69bAKnn7Mxk4hoaHgTt/XCXyGLtTDo+sVSeLj685K9lrABp3c+FbmtOQSj7/xks7CjoLekcOP5u35iwJkehlTrwMv1tHXSV+Ns1Dpex0dOXkdsNnKypag1tNj5D7zrnVrl+mBNPZzvp3Z1og8nVYM6f04z9Ke4e/EOQO9kvX55pqvpHj+dqqkpCHNUR4JDb4K3pl7dOYdgxlmKELEKtAYTsA0bmRQRxzAA9Fs9I5IKO9tGFbl+oBI99zBB+Vyv/soWFrYRh7w8OpD3Bnh9nT8Wudzvt31jye0PNRv9f9YGsSctqsjvE3Z0wH3X+gq8TVjcZeoTfNa2Xr6JOHk0vGH1twHjYZlRK5B3xQyf4uBDWgYoet4ihL8gvka65ofJ9QHzVk46CIUEj0LfyfPbOizMq9yPFLfAGgksycghli4Q2YmI2yrQvByk1UXp4zTcv+9Qq/mu1OKC71zHfiTX+TqrVfGPmS/AbNarNpls9zeG+q3+ZRmm63EmIGCBFZAaiXWmdTsJ4DBJF0wOr8hdY4OMP9avrmLCQ6GqWoUGAiSiBcy7gZM2cwvEzYqEPV6Fuak/8aBz1/mHlGvuFPfzEJYBzMk4H0b3O8n63ZAyutpxKpO7mXsrtulTiTgY8YVGS3dO/TczAkxnQqS8=
  file: hJOPquiz.pdf hJOPquizKey.pdf
  skip_cleanup: true
  on:
    tags: true
